file= open("aa.txt",'r+')
print(file.closed)
print(file.mode)
print(file.encoding)
print(file.name)
print(file.readline())
print(file.readline())
file.seek(0)
print(file.read())
print(file.tell())
file.write('你好 python！')
file.seek(0)
print(file.read())
str1=['hello world!','这是一个测试！、\n','这是一个test!']
file.writelines(str1)
file.seek(0)
print(file.read())
file.seek(0)
print(file.readlines())
file.close()
